### ISSUE TITLE
code bug！？

### ISSUE THREAD

**Issue by bluoluo** [microsoft/PySiamTracking#1]
* 1、I only have the GOT10k data set for the time being. When I use the script to generate the cut image, I found that the image cannot be read, and the debug finds that there is a problem with the file path.
I added two lines of code in converter.py for the time being (for got10k), as follows

![image](https://user-images.githubusercontent.com/45422842/78502092-d70ae480-7791-11ea-974d-d1857f4ee803.png)

Hope to fix this bug！

* 2、The following errors occurred during training:
> Connected to pydev debugger (build 193.5233.109)
2020-04-05 21:11:43,790 - INFO - Set random seed to 7
2020-04-05 21:11:43,840 - INFO - Loading pretrained model from data/pretrained_models/resnet18.pth
Traceback (most recent call last):
  File "/opt/pycharm-anaconda-2019.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-anaconda-2019.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/bluo/git_clone/PySiamTracking/tools/train_tracker.py", line 93, in <module>
    gpus=cfg.gpus)
  File "/home/bluo/git_clone/PySiamTracking/siam_tracker/models/builder.py", line 57, in build_train_wrapper
    train_wrapper = TRAIN_WRAPPERS.get_module(training_type)(train_cfg=train_cfg, *args, **kwargs)
  File "/home/bluo/git_clone/PySiamTracking/siam_tracker/models/train_wrappers/pairwise_wrapper.py", line 44, in __init__
    train_dataset = TrainPairDataset(train_cfg.train_data)
  File "/home/bluo/git_clone/PySiamTracking/siam_tracker/datasets/train_pair_dataset.py", line 23, in __init__
    self._load_datasets(data_cfg.datasets)
  File "/home/bluo/git_clone/PySiamTracking/siam_tracker/datasets/train_pair_dataset.py", line 101, in _load_datasets
    self.dataset_list.append(ImageDataset(**_cfg))      # !
  File "/home/bluo/git_clone/PySiamTracking/siam_tracker/datasets/image_dataset.py", line 51, in __init__
    self._load_dataset()
  File "/home/bluo/git_clone/PySiamTracking/siam_tracker/datasets/image_dataset.py", line 191, in _load_dataset
    self._load_pkl_annotation(anno_file_path)
  File "/home/bluo/git_clone/PySiamTracking/siam_tracker/datasets/image_dataset.py", line 175, in _load_pkl_annotation
    assert valid_inds[0]
AssertionError

Debug found that whenever seq_id=4224, valid_inds=False, I know this is to delete some invalid boxes, but why not continue to execute?

![pysiamtracking_image_dataset](https://user-images.githubusercontent.com/45422842/78502327-3ae1dd00-7793-11ea-898e-e76833a04f82.png)

**Comment by wgting96** [comment]
The `valid_inds[0]` is necessary to be `True` because we assume that the first item (index-0) is the core bounding-box in the image patch. The image patch is cropped according to this bounding box. If it's a invalid box, the cropped image is also invalid.  To make sure every bounding box is correct, I temporarily wrote a script to clean the annotations but forgot to merge it into the code base. 

I will double-check the pre-processing code and update it.

Thanks for catching this bug.

**Comment by wgting96** [comment]
Fixed.

You can also directly download the pre-processed datasets. See details in https://github.com/microsoft/PySiamTracking/blob/master/docs/train.md

**Comment by bluoluo** [comment]
Thank you very much for your reply, your work is great, the code is very well written!
I have not yet modified the code according to your prompt. But there may be a bug,
`image_dataset.py`
> valid_inds = np.where(np.abs(frame_inds - frame_inds[z_id[1]]) <= self.max_frame_dist)[0]

The error is prompted here:
> unsupported operand type(s) for -: 'list' and 'int'

I dealt with this temporarily:
> b = frame_inds[z_id[1]]
   frame_inds[:] = [x - b for x in frame_inds]
   valid_inds = np.where(np.abs(frame_inds) <= self.max_frame_dist)[0]

Later, I will modify the code according to your prompt, and then give feedback.

**Comment by bluoluo** [comment]
Thank you very much for providing the pre-processing training dataset, it is recommended to use `AzCopy` to download(from`wgting96`).
For an introduction to AzCopy, please refer to [here](https://docs.microsoft.com/zh-cn/azure/storage/common/storage-use-azcopy-v10#use-azcopy-in-a-script).
Windows：
```
AzCopy /Source:https://imgtracking.blob.core.windows.net/pysiamtracking/data/LaSOT_trian_images.zip /Dest:LaSOT_trian_images.zip
```
linux：
```
azcopy cp "https://imgtracking.blob.core.windows.net/pysiamtracking/data/LaSOT_trian_images.zip" "/home/xxx/dataset/" 
```
Just replace the download link and the storage address.
